/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer;

import carrental.welcome;

/**
 *
 * @author yukti
 */
public class about extends javax.swing.JFrame {

    /**
     * Creates new form about
     */
    public about() {
        initComponents();
        String name = userLogin.name;
        txtwelcome.setText(name);
        String username = userLogin.username;   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        sidepane = new javax.swing.JPanel();
        txtwelcome = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();
        rental = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        carRegister = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();
        myRents = new javax.swing.JButton();
        cancelRent = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea1.setBackground(new java.awt.Color(54, 33, 89));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea1.setRows(5);
        jTextArea1.setText("THIS IS A CAR RENTAL MANAGEMENT PROJECT IN JAVA  BY\n\t     YUKTI KHURANA\n\t    ");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 680, 410));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("About us");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 480, 140));

        sidepane.setBackground(new java.awt.Color(54, 33, 89));
        sidepane.setPreferredSize(new java.awt.Dimension(244, 534));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtwelcome.setBackground(new java.awt.Color(255, 255, 255));
        txtwelcome.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txtwelcome.setForeground(new java.awt.Color(204, 204, 204));
        txtwelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtwelcome.setText("Home");
        sidepane.add(txtwelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, 50));

        updatebtn.setBackground(new java.awt.Color(85, 65, 118));
        updatebtn.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        updatebtn.setForeground(new java.awt.Color(204, 204, 204));
        updatebtn.setText("Update Profile");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        sidepane.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 260, 50));

        rental.setBackground(new java.awt.Color(85, 65, 118));
        rental.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        rental.setForeground(new java.awt.Color(204, 204, 204));
        rental.setText("Rent History");
        rental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalActionPerformed(evt);
            }
        });
        sidepane.add(rental, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 260, 50));

        exit.setBackground(new java.awt.Color(85, 65, 118));
        exit.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        exit.setForeground(new java.awt.Color(204, 204, 204));
        exit.setText("Logout");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        sidepane.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 260, 50));

        carRegister.setBackground(new java.awt.Color(85, 65, 118));
        carRegister.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        carRegister.setForeground(new java.awt.Color(204, 204, 204));
        carRegister.setText("Rent Car");
        carRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carRegisterActionPerformed(evt);
            }
        });
        sidepane.add(carRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 260, 50));

        aboutBtn.setBackground(new java.awt.Color(85, 65, 118));
        aboutBtn.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        aboutBtn.setForeground(new java.awt.Color(204, 204, 204));
        aboutBtn.setText("About");
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });
        sidepane.add(aboutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 260, 50));

        myRents.setBackground(new java.awt.Color(85, 65, 118));
        myRents.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        myRents.setForeground(new java.awt.Color(204, 204, 204));
        myRents.setText("My Rents");
        myRents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myRentsActionPerformed(evt);
            }
        });
        sidepane.add(myRents, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 260, 50));

        cancelRent.setBackground(new java.awt.Color(85, 65, 118));
        cancelRent.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        cancelRent.setForeground(new java.awt.Color(204, 204, 204));
        cancelRent.setText("Cancel Rent");
        cancelRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelRentActionPerformed(evt);
            }
        });
        sidepane.add(cancelRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 260, 50));

        getContentPane().add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 700));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrental/images/carback.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        dispose();
        updateProfile u = new updateProfile();
        u.setVisible(true);
    }//GEN-LAST:event_updatebtnActionPerformed

    private void rentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalActionPerformed
        dispose();
        RentHistory rh = new RentHistory();
        rh.setVisible(true);
    }//GEN-LAST:event_rentalActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose();
        welcome w = new welcome();
        w.setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    private void carRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carRegisterActionPerformed
        dispose();
        rentACar r = new rentACar();
        r.setVisible(true);
    }//GEN-LAST:event_carRegisterActionPerformed

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        
    }//GEN-LAST:event_aboutBtnActionPerformed

    private void myRentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myRentsActionPerformed
        dispose();
        myRents w = new myRents();
        w.setVisible(true);

    }//GEN-LAST:event_myRentsActionPerformed

    private void cancelRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelRentActionPerformed
        dispose();  
        cancelRent r = new cancelRent();
           r.setVisible(true);
    }//GEN-LAST:event_cancelRentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new about().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutBtn;
    private javax.swing.JButton cancelRent;
    private javax.swing.JButton carRegister;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton myRents;
    private javax.swing.JButton rental;
    private javax.swing.JPanel sidepane;
    private javax.swing.JLabel txtwelcome;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
