/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer;

import Admin.carRegistration;
import carrental.welcome;
import extra.customerRegistration;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author yukti
 */
public class cancelRent extends javax.swing.JFrame {

    /**
     * Creates new form cancelRent
     */
    public cancelRent() {
        initComponents();
    }
      Connection con;
    PreparedStatement pst,pst1,pst2,pst3;
    ResultSet rs,rs2;  
    String custid = userLogin.cust_id;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtreason = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        carid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        updatePassword = new javax.swing.JPasswordField();
        updatePhone1 = new javax.swing.JTextField();
        updatePassword1 = new javax.swing.JPasswordField();
        updatePhone2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sidepane = new javax.swing.JPanel();
        txtwelcome = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();
        myRents = new javax.swing.JButton();
        carRegister = new javax.swing.JButton();
        rentHistory = new javax.swing.JButton();
        cancelRent = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtreason.setColumns(20);
        txtreason.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtreason.setRows(5);
        jScrollPane1.setViewportView(txtreason);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 200, 180));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Reason?");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 110, 60));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Car ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 110, 60));

        cancelBtn.setBackground(new java.awt.Color(255, 255, 255));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(54, 33, 89));
        cancelBtn.setText("Cancel Car");
        cancelBtn.setBorder(null);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 545, 120, 40));

        carid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        carid.setBorder(null);
        getContentPane().add(carid, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 180, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Any problems? Contact us : 9998909181");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 640, 390, 60));

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cancel Rent", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 17), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("For car id refer to \"My rents\"");
        jPanel2.add(jLabel10);

        updatePassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updatePassword.setBorder(null);
        jPanel2.add(updatePassword);

        updatePhone1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updatePhone1.setBorder(null);
        jPanel2.add(updatePhone1);

        updatePassword1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updatePassword1.setBorder(null);
        jPanel2.add(updatePassword1);

        updatePhone2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updatePhone2.setBorder(null);
        jPanel2.add(updatePhone2);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 520, 520));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cancel Car");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 320, 90));

        sidepane.setBackground(new java.awt.Color(54, 33, 89));
        sidepane.setPreferredSize(new java.awt.Dimension(244, 534));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtwelcome.setBackground(new java.awt.Color(255, 255, 255));
        txtwelcome.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txtwelcome.setForeground(new java.awt.Color(204, 204, 204));
        txtwelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtwelcome.setText("Home");
        sidepane.add(txtwelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, 50));

        updatebtn.setBackground(new java.awt.Color(85, 65, 118));
        updatebtn.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        updatebtn.setForeground(new java.awt.Color(204, 204, 204));
        updatebtn.setText("Update Profile");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        sidepane.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 260, 50));

        aboutBtn.setBackground(new java.awt.Color(85, 65, 118));
        aboutBtn.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        aboutBtn.setForeground(new java.awt.Color(204, 204, 204));
        aboutBtn.setText("About");
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });
        sidepane.add(aboutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 260, 50));

        myRents.setBackground(new java.awt.Color(85, 65, 118));
        myRents.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        myRents.setForeground(new java.awt.Color(204, 204, 204));
        myRents.setText("My Rents");
        myRents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myRentsActionPerformed(evt);
            }
        });
        sidepane.add(myRents, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 260, 50));

        carRegister.setBackground(new java.awt.Color(85, 65, 118));
        carRegister.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        carRegister.setForeground(new java.awt.Color(204, 204, 204));
        carRegister.setText("Rent Car");
        carRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carRegisterActionPerformed(evt);
            }
        });
        sidepane.add(carRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 260, 50));

        rentHistory.setBackground(new java.awt.Color(85, 65, 118));
        rentHistory.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        rentHistory.setForeground(new java.awt.Color(204, 204, 204));
        rentHistory.setText("Rent History");
        rentHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentHistoryActionPerformed(evt);
            }
        });
        sidepane.add(rentHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 260, 50));

        cancelRent.setBackground(new java.awt.Color(85, 65, 118));
        cancelRent.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        cancelRent.setForeground(new java.awt.Color(204, 204, 204));
        cancelRent.setText("Cancel Rent");
        cancelRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelRentActionPerformed(evt);
            }
        });
        sidepane.add(cancelRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 260, 50));

        logout.setBackground(new java.awt.Color(85, 65, 118));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        logout.setForeground(new java.awt.Color(204, 204, 204));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        sidepane.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 260, 50));

        getContentPane().add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 700));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrental/images/carback.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        dispose();
        updateProfile u = new updateProfile();
        u.setVisible(true);
    }//GEN-LAST:event_updatebtnActionPerformed

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        dispose();
        about a = new about();
        a.setVisible(true);
    }//GEN-LAST:event_aboutBtnActionPerformed

    private void myRentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myRentsActionPerformed
        dispose();
        myRents w = new myRents();
        w.setVisible(true);

    }//GEN-LAST:event_myRentsActionPerformed

    private void carRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carRegisterActionPerformed
        dispose();
        rentACar r = new rentACar();
        r.setVisible(true);
    }//GEN-LAST:event_carRegisterActionPerformed

    private void rentHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentHistoryActionPerformed
        dispose();
        RentHistory rh = new RentHistory();
        rh.setVisible(true);
    }//GEN-LAST:event_rentHistoryActionPerformed

    private void cancelRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelRentActionPerformed
        
    }//GEN-LAST:event_cancelRentActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        dispose();
        welcome w = new welcome();
        w.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed
    public String autoID(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/cars","root","");            
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("select Max(id) from carscancelled");
            rs.next();
            rs.getString("Max(id)");
            if (rs.getString("Max(id)")==null){
                return "CE0001";
            }else{
                long id = Long.parseLong(rs.getString("Max(id)").substring(2,rs.getString("Max(id)").length()));
                System.out.println("RENTAL ID  = "+id);
                id++;
                String r = "CE0"+String.format("%03d",id);
                return r;
            }            
        }catch(ClassNotFoundException ex){
            Logger.getLogger(carRegistration.class.getName()).log(Level.SEVERE,null,ex);            
        }catch(SQLException ex){
            Logger.getLogger(carRegistration.class.getName()).log(Level.SEVERE,null,ex);
        }
        return null;        
    }
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        String id = carid.getText();
        String reason = txtreason.getText();
        if (id.equals("")){
            JOptionPane.showMessageDialog(this,"Please enter the car id"); 
        }else{
            if (reason.equals("")){
                JOptionPane.showMessageDialog(this,"Please enter a reason for cancellation!!"); 
            }else{
            }
                 try{                
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/cars","root","");            
                Statement s = con.createStatement();
                pst3 = con.prepareStatement("select * from rental where car_id = ? and cust_id = ?");
                System.out.println(id);
                pst3.setString(1,id);
                pst3.setString(2,custid);
                rs2 = pst3.executeQuery();
                
                String rentalid;
                if (rs2.next()){                   
                    rentalid = rs2.getString("id");
                     DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                Date date = new Date();
                System.out.println(dateFormat.format(date)); 
                String nowdate;                
                nowdate = String.valueOf(dateFormat.format(date));
                pst = con.prepareStatement("insert into carscancelled(id,rental_id,car_id,cust_id,reason,date) values(?,?,?,?,?,?)");
                 pst.setString(1,autoID());
                pst.setString(2,rentalid);
                pst.setString(3,id);
                pst.setString(4,custid);
                pst.setString(5,reason);
                pst.setString(6,nowdate);
                pst.executeUpdate();                
                // make the car available
                pst1 = con.prepareStatement("update carsrental set available = 'Yes' where car_id = ? ");
                pst1.setString(1,id);                
                pst1.executeUpdate();
                // delete correspoding rent record from rental table
                pst2 = con.prepareStatement("delete from rental where car_id = ? and cust_id = ?");
                pst2.setString(1,id);
                pst2.setString(2,custid);
                pst2.executeUpdate();
                
                JOptionPane.showMessageDialog(this,"Car cancelled Successfully!");
                carid.setText("");
                txtreason.setText("");
                }else{
                    JOptionPane.showMessageDialog(this,"Sorry! You have rented NO such car!");
                    carid.setText("");
                    txtreason.setText("");
                    return ;
                }
               
                
               
            }catch(ClassNotFoundException ex){
                Logger.getLogger(customerRegistration.class.getName()).log(Level.SEVERE,null,ex);            
            }catch(SQLException ex){
                Logger.getLogger(customerRegistration.class.getName()).log(Level.SEVERE,null,ex);
            }        
        
        
                                                
            }
        

    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cancelRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cancelRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cancelRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cancelRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cancelRent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton cancelRent;
    private javax.swing.JButton carRegister;
    private javax.swing.JTextField carid;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JButton myRents;
    private javax.swing.JButton rentHistory;
    private javax.swing.JPanel sidepane;
    private javax.swing.JTextArea txtreason;
    private javax.swing.JLabel txtwelcome;
    private javax.swing.JPasswordField updatePassword;
    private javax.swing.JPasswordField updatePassword1;
    private javax.swing.JTextField updatePhone1;
    private javax.swing.JTextField updatePhone2;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
