/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer;

import carrental.welcome;
import extra.customerRegistration;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author yukti
 */
public class RentHistory extends javax.swing.JFrame {

    /**
     * Creates new form RentHistory
     */
    public RentHistory() {
        initComponents();
        table_font();
        table_update();
        String userName = userLogin.name;
        txtwelcome.setText(userName);
        
    }
    String custid = userLogin.cust_id;
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    String rentalID;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rentsTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        sidepane = new javax.swing.JPanel();
        txtwelcome = new javax.swing.JLabel();
        sidepane1 = new javax.swing.JPanel();
        txtwelcome1 = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        carRegister = new javax.swing.JButton();
        rental1 = new javax.swing.JButton();
        myRents = new javax.swing.JButton();
        cancelRent1 = new javax.swing.JButton();
        cancelRent2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cancelRent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car ID", "Rent Date", "Return Date", "Late days", "Fine", "Total Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(rentsTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 160, 700, 470));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Previous Rents");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 450, 110));

        sidepane.setBackground(new java.awt.Color(54, 33, 89));
        sidepane.setPreferredSize(new java.awt.Dimension(244, 534));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtwelcome.setBackground(new java.awt.Color(255, 255, 255));
        txtwelcome.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txtwelcome.setForeground(new java.awt.Color(204, 204, 204));
        txtwelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtwelcome.setText("Home");
        sidepane.add(txtwelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, 50));

        sidepane1.setBackground(new java.awt.Color(54, 33, 89));
        sidepane1.setPreferredSize(new java.awt.Dimension(244, 534));
        sidepane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtwelcome1.setBackground(new java.awt.Color(255, 255, 255));
        txtwelcome1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txtwelcome1.setForeground(new java.awt.Color(204, 204, 204));
        txtwelcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtwelcome1.setText("Home");
        sidepane1.add(txtwelcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, 50));

        updatebtn.setBackground(new java.awt.Color(85, 65, 118));
        updatebtn.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        updatebtn.setForeground(new java.awt.Color(204, 204, 204));
        updatebtn.setText("Update Profile");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        sidepane1.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 260, 50));

        aboutBtn.setBackground(new java.awt.Color(85, 65, 118));
        aboutBtn.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        aboutBtn.setForeground(new java.awt.Color(204, 204, 204));
        aboutBtn.setText("About");
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });
        sidepane1.add(aboutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 260, 50));

        exit.setBackground(new java.awt.Color(85, 65, 118));
        exit.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        exit.setForeground(new java.awt.Color(204, 204, 204));
        exit.setText("Logout");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        sidepane1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 260, 50));

        carRegister.setBackground(new java.awt.Color(85, 65, 118));
        carRegister.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        carRegister.setForeground(new java.awt.Color(204, 204, 204));
        carRegister.setText("Rent Car");
        carRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carRegisterActionPerformed(evt);
            }
        });
        sidepane1.add(carRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 260, 50));

        rental1.setBackground(new java.awt.Color(85, 65, 118));
        rental1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        rental1.setForeground(new java.awt.Color(204, 204, 204));
        rental1.setText("Rent History");
        rental1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rental1ActionPerformed(evt);
            }
        });
        sidepane1.add(rental1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 260, 50));

        myRents.setBackground(new java.awt.Color(85, 65, 118));
        myRents.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        myRents.setForeground(new java.awt.Color(204, 204, 204));
        myRents.setText("My Rents");
        myRents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myRentsActionPerformed(evt);
            }
        });
        sidepane1.add(myRents, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 260, 50));

        cancelRent1.setBackground(new java.awt.Color(85, 65, 118));
        cancelRent1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        cancelRent1.setForeground(new java.awt.Color(204, 204, 204));
        cancelRent1.setText("Cancel Rent");
        cancelRent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelRent1ActionPerformed(evt);
            }
        });
        sidepane1.add(cancelRent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 260, 50));

        cancelRent2.setBackground(new java.awt.Color(85, 65, 118));
        cancelRent2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        cancelRent2.setForeground(new java.awt.Color(204, 204, 204));
        cancelRent2.setText("Cancel Rent");
        cancelRent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelRent2ActionPerformed(evt);
            }
        });
        sidepane1.add(cancelRent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 260, 50));

        sidepane.add(sidepane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 700));

        getContentPane().add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 700));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrental/images/carback.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 700));

        cancelRent.setBackground(new java.awt.Color(85, 65, 118));
        cancelRent.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        cancelRent.setForeground(new java.awt.Color(204, 204, 204));
        cancelRent.setText("Cancel Rent");
        cancelRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelRentActionPerformed(evt);
            }
        });
        getContentPane().add(cancelRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 260, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        dispose();
        updateProfile u = new updateProfile();
        u.setVisible(true);
    }//GEN-LAST:event_updatebtnActionPerformed

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        dispose();
        about a = new about();
        a.setVisible(true);
    }//GEN-LAST:event_aboutBtnActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose();
        welcome w = new welcome();
        w.setVisible(true);

    }//GEN-LAST:event_exitActionPerformed

    private void carRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carRegisterActionPerformed
        dispose();
        rentACar r = new rentACar();
        r.setVisible(true);
    }//GEN-LAST:event_carRegisterActionPerformed

    private void rental1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rental1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rental1ActionPerformed

    private void myRentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myRentsActionPerformed
        dispose();
        myRents w = new myRents();
        w.setVisible(true);

    }//GEN-LAST:event_myRentsActionPerformed

    private void cancelRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelRentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelRentActionPerformed

    private void cancelRent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelRent1ActionPerformed
      dispose();  
        cancelRent r = new cancelRent();
           r.setVisible(true);
    }//GEN-LAST:event_cancelRent1ActionPerformed

    private void cancelRent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelRent2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelRent2ActionPerformed

    public void table_font(){
        rentsTable.setBackground(Color.decode("#554176"));        
        // set Font To table
        rentsTable.setFont(new Font("", 1, 15));        
        // set height to the table rows
        rentsTable.setRowHeight(25);        
        // set color to the JTable Font
        rentsTable.setForeground(Color.white);        
        rentsTable.setFont(new Font("", 1, 15));
        rentsTable.setForeground(Color.white);
        rentsTable.setBackground(Color.decode("#362159"));
        rentsTable.setPreferredScrollableViewportSize(new Dimension(500, 70)); 
        // set font for headers
        Font f = new Font("Calibri", Font.BOLD, 22);
        JTableHeader header = rentsTable.getTableHeader();
        header.setFont(f);
        header.setBackground(Color.decode("#362159"));
        header.setForeground(Color.white);    
        
    }
    public void table_update(){
        
         try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/cars","root","");            
            pst = con.prepareStatement("select * from carsreturned where cust_id = ?"); 
            pst.setString(1,custid);
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData rd = rs.getMetaData();
            int c = rd.getColumnCount();
            DefaultTableModel df = (DefaultTableModel)rentsTable.getModel();
            df.setRowCount(0);
            while(rs.next()){
                Vector v2 = new Vector();
                for(int i=1;i<=c;i++){
                    //v2.add(rs.getString("return_id"));
                    //v2.add(rs.getString("cust_id"));
                    v2.add(rs.getString("car_id"));
                    v2.add(rs.getString("rentalDate")); 
                    v2.add(rs.getString("returnDate"));
                    v2.add(rs.getString("lateDays")); 
                    v2.add(rs.getString("fine"));  
                    v2.add(rs.getString("totalCost")); 
                }
                df.addRow(v2);            
            }     
            
        }catch(ClassNotFoundException ex){
            Logger.getLogger(customerRegistration.class.getName()).log(Level.SEVERE,null,ex);            
        }catch(SQLException ex){
            Logger.getLogger(customerRegistration.class.getName()).log(Level.SEVERE,null,ex);
        }        
    }    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutBtn;
    private javax.swing.JButton cancelRent;
    private javax.swing.JButton cancelRent1;
    private javax.swing.JButton cancelRent2;
    private javax.swing.JButton carRegister;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton myRents;
    private javax.swing.JButton rental1;
    private javax.swing.JTable rentsTable;
    private javax.swing.JPanel sidepane;
    private javax.swing.JPanel sidepane1;
    private javax.swing.JLabel txtwelcome;
    private javax.swing.JLabel txtwelcome1;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
