/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer;

import carrental.welcome;

public class userHome extends javax.swing.JFrame {

    public userHome() {
        initComponents();
        String userName;
        userName = userLogin.name;
        txtwelcome.setText(userName);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sidepane = new javax.swing.JPanel();
        txtwelcome = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();
        myRents = new javax.swing.JButton();
        carRegister = new javax.swing.JButton();
        rentHistory = new javax.swing.JButton();
        cancelRent = new javax.swing.JButton();
        exit2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe Script", 1, 45)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Don't Dream it, Drive it..");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 640, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 100)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CAR RENTAL");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 610, 130));

        sidepane.setBackground(new java.awt.Color(54, 33, 89));
        sidepane.setPreferredSize(new java.awt.Dimension(244, 534));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtwelcome.setBackground(new java.awt.Color(255, 255, 255));
        txtwelcome.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        txtwelcome.setForeground(new java.awt.Color(204, 204, 204));
        txtwelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtwelcome.setText("Home");
        sidepane.add(txtwelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, 50));

        updatebtn.setBackground(new java.awt.Color(85, 65, 118));
        updatebtn.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        updatebtn.setForeground(new java.awt.Color(204, 204, 204));
        updatebtn.setText("Update Profile");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        sidepane.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 260, 50));

        aboutBtn.setBackground(new java.awt.Color(85, 65, 118));
        aboutBtn.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        aboutBtn.setForeground(new java.awt.Color(204, 204, 204));
        aboutBtn.setText("About");
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });
        sidepane.add(aboutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 260, 50));

        myRents.setBackground(new java.awt.Color(85, 65, 118));
        myRents.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        myRents.setForeground(new java.awt.Color(204, 204, 204));
        myRents.setText("My Rents");
        myRents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myRentsActionPerformed(evt);
            }
        });
        sidepane.add(myRents, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 260, 50));

        carRegister.setBackground(new java.awt.Color(85, 65, 118));
        carRegister.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        carRegister.setForeground(new java.awt.Color(204, 204, 204));
        carRegister.setText("Rent Car");
        carRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carRegisterActionPerformed(evt);
            }
        });
        sidepane.add(carRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 260, 50));

        rentHistory.setBackground(new java.awt.Color(85, 65, 118));
        rentHistory.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        rentHistory.setForeground(new java.awt.Color(204, 204, 204));
        rentHistory.setText("Rent History");
        rentHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentHistoryActionPerformed(evt);
            }
        });
        sidepane.add(rentHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 260, 50));

        cancelRent.setBackground(new java.awt.Color(85, 65, 118));
        cancelRent.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        cancelRent.setForeground(new java.awt.Color(204, 204, 204));
        cancelRent.setText("Cancel Rent");
        cancelRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelRentActionPerformed(evt);
            }
        });
        sidepane.add(cancelRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 260, 50));

        exit2.setBackground(new java.awt.Color(85, 65, 118));
        exit2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        exit2.setForeground(new java.awt.Color(204, 204, 204));
        exit2.setText("Logout");
        exit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit2ActionPerformed(evt);
            }
        });
        sidepane.add(exit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 260, 50));

        getContentPane().add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 700));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrental/images/carback.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 700));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 100)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CAR RENTAL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 610, 130));

        jLabel4.setFont(new java.awt.Font("Segoe Script", 1, 45)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Don't Dream it, Drive it..");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 640, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        dispose();
        updateProfile u = new updateProfile();
        u.setVisible(true);
    }//GEN-LAST:event_updatebtnActionPerformed

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        dispose();
        about a = new about();
        a.setVisible(true);
    }//GEN-LAST:event_aboutBtnActionPerformed

    private void myRentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myRentsActionPerformed
        dispose();
        myRents w = new myRents();
        w.setVisible(true);
        
    }//GEN-LAST:event_myRentsActionPerformed

    private void carRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carRegisterActionPerformed
        dispose();
        rentACar r = new rentACar();
        r.setVisible(true);
    }//GEN-LAST:event_carRegisterActionPerformed

    private void rentHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentHistoryActionPerformed
        dispose();
        RentHistory rh = new RentHistory();
        rh.setVisible(true);
    }//GEN-LAST:event_rentHistoryActionPerformed

    private void cancelRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelRentActionPerformed
        dispose();  
        cancelRent r = new cancelRent();
           r.setVisible(true);
    }//GEN-LAST:event_cancelRentActionPerformed

    private void exit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit2ActionPerformed
       dispose();
        welcome w = new welcome();
        w.setVisible(true);
    }//GEN-LAST:event_exit2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutBtn;
    private javax.swing.JButton cancelRent;
    private javax.swing.JButton carRegister;
    private javax.swing.JButton exit2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton myRents;
    private javax.swing.JButton rentHistory;
    private javax.swing.JPanel sidepane;
    private javax.swing.JLabel txtwelcome;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
