/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Admin.carRegistration;
import Admin.users;
import carrental.welcome;

/**
 *
 * @author yukti
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
       
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sidepane = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        customers = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        carRegister = new javax.swing.JButton();
        defaulters = new javax.swing.JButton();
        returnCar = new javax.swing.JButton();
        cancelledRents = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 100)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CAR RENTAL");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 610, 130));

        jLabel5.setFont(new java.awt.Font("Segoe Script", 1, 45)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Don't Dream it, Drive it..");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 640, 50));

        sidepane.setBackground(new java.awt.Color(54, 33, 89));
        sidepane.setPreferredSize(new java.awt.Dimension(244, 534));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Microsoft Tai Le", 1, 30)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Home");
        sidepane.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 110, 50));

        customers.setBackground(new java.awt.Color(85, 65, 118));
        customers.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        customers.setForeground(new java.awt.Color(204, 204, 204));
        customers.setText("Customers");
        customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersActionPerformed(evt);
            }
        });
        sidepane.add(customers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 260, 50));

        exit.setBackground(new java.awt.Color(85, 65, 118));
        exit.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        exit.setForeground(new java.awt.Color(204, 204, 204));
        exit.setText("Logout");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        sidepane.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 260, 50));

        carRegister.setBackground(new java.awt.Color(85, 65, 118));
        carRegister.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        carRegister.setForeground(new java.awt.Color(204, 204, 204));
        carRegister.setText("Car Registration");
        carRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carRegisterActionPerformed(evt);
            }
        });
        sidepane.add(carRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 260, 50));

        defaulters.setBackground(new java.awt.Color(85, 65, 118));
        defaulters.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        defaulters.setForeground(new java.awt.Color(204, 204, 204));
        defaulters.setText("Rental Info");
        defaulters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultersActionPerformed(evt);
            }
        });
        sidepane.add(defaulters, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 260, 50));

        returnCar.setBackground(new java.awt.Color(85, 65, 118));
        returnCar.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        returnCar.setForeground(new java.awt.Color(204, 204, 204));
        returnCar.setText("Cars Returned");
        returnCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnCarActionPerformed(evt);
            }
        });
        sidepane.add(returnCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 260, 50));

        cancelledRents.setBackground(new java.awt.Color(85, 65, 118));
        cancelledRents.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        cancelledRents.setForeground(new java.awt.Color(204, 204, 204));
        cancelledRents.setText("Cancelled Rents");
        cancelledRents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelledRentsActionPerformed(evt);
            }
        });
        sidepane.add(cancelledRents, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 260, 50));

        getContentPane().add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 700));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrental/images/carback.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersActionPerformed
        dispose();
        users c = new users();
        c.setVisible(true);
    }//GEN-LAST:event_customersActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose();
        welcome w = new welcome();
        w.setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    private void carRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carRegisterActionPerformed
        carRegistration c = new carRegistration();
        c.setVisible(true);
    }//GEN-LAST:event_carRegisterActionPerformed

    private void defaultersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultersActionPerformed
        dispose();
        rentalInfo d = new rentalInfo();
        d.setVisible(true);
    }//GEN-LAST:event_defaultersActionPerformed

    private void returnCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnCarActionPerformed
       
        returnCar r =  new returnCar();
        r.setVisible(true);
    }//GEN-LAST:event_returnCarActionPerformed

    private void cancelledRentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelledRentsActionPerformed
      dispose();
        cancelledRecords c = new cancelledRecords();
      c.setVisible(true);
      
    }//GEN-LAST:event_cancelledRentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelledRents;
    private javax.swing.JButton carRegister;
    private javax.swing.JButton customers;
    private javax.swing.JButton defaulters;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton returnCar;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables
}
