/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Admin.carRegistration;
import carrental.welcome;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import extra.customerRegistration;

/**
 *
 * @author yukti
 */
public class users extends javax.swing.JFrame {

    /**
     * Creates new form users
     */
    public users() {
        initComponents();
         
        table_font();
        table_update();
    }
    Connection con;
    PreparedStatement pst,pst1;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoTable = new javax.swing.JScrollPane();
        custTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        sidepane = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        defaulters = new javax.swing.JButton();
        returnCar = new javax.swing.JButton();
        customers = new javax.swing.JButton();
        carRegister = new javax.swing.JButton();
        cancelledRents = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        custTable.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        custTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CUSTOMER ID", "AADHAR NO", "LICENCE NO", "RATING"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        custTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                custTableMouseClicked(evt);
            }
        });
        infoTable.setViewportView(custTable);

        getContentPane().add(infoTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 590, 440));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Customers ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 340, 70));

        sidepane.setBackground(new java.awt.Color(54, 33, 89));
        sidepane.setPreferredSize(new java.awt.Dimension(244, 534));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Microsoft Tai Le", 1, 30)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Home");
        sidepane.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 110, 50));

        exit.setBackground(new java.awt.Color(85, 65, 118));
        exit.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        exit.setForeground(new java.awt.Color(204, 204, 204));
        exit.setText("Logout");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        sidepane.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 260, 50));

        defaulters.setBackground(new java.awt.Color(85, 65, 118));
        defaulters.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        defaulters.setForeground(new java.awt.Color(204, 204, 204));
        defaulters.setText("Rental Info");
        defaulters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultersActionPerformed(evt);
            }
        });
        sidepane.add(defaulters, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 260, 50));

        returnCar.setBackground(new java.awt.Color(85, 65, 118));
        returnCar.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        returnCar.setForeground(new java.awt.Color(204, 204, 204));
        returnCar.setText("Cars Returned");
        returnCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnCarActionPerformed(evt);
            }
        });
        sidepane.add(returnCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 260, 50));

        customers.setBackground(new java.awt.Color(85, 65, 118));
        customers.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        customers.setForeground(new java.awt.Color(204, 204, 204));
        customers.setText("Customers");
        customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersActionPerformed(evt);
            }
        });
        sidepane.add(customers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 260, 50));

        carRegister.setBackground(new java.awt.Color(85, 65, 118));
        carRegister.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        carRegister.setForeground(new java.awt.Color(204, 204, 204));
        carRegister.setText("Car Registration");
        carRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carRegisterActionPerformed(evt);
            }
        });
        sidepane.add(carRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 260, 50));

        cancelledRents.setBackground(new java.awt.Color(85, 65, 118));
        cancelledRents.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        cancelledRents.setForeground(new java.awt.Color(204, 204, 204));
        cancelledRents.setText("Cancelled Rents");
        cancelledRents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelledRentsActionPerformed(evt);
            }
        });
        sidepane.add(cancelledRents, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 260, 50));

        getContentPane().add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 700));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrental/images/carback.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void table_font(){
        custTable.setBackground(Color.decode("#554176"));        
        // set Font To table
        custTable.setFont(new Font("", 1, 20));        
        // set height to the table rows
        custTable.setRowHeight(25);        
        // set color to the JTable Font
        custTable.setForeground(Color.white);        
        infoTable.setFont(new Font("", 1, 20));
        infoTable.setForeground(Color.white);
        infoTable.setBackground(Color.decode("#362159"));
        custTable.setPreferredScrollableViewportSize(new Dimension(500, 70)); 
        // set font for headers
        Font f = new Font("Calibri", Font.BOLD, 22);
        JTableHeader header = custTable.getTableHeader();
        header.setFont(f);
        header.setBackground(Color.decode("#362159"));
        header.setForeground(Color.white);    
        
    }
    public void table_update(){
        int c;
         try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/cars","root","");            
            pst = con.prepareStatement("select * from custSecurity");  
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData rd = rs.getMetaData();
            c = rd.getColumnCount();
            DefaultTableModel df = (DefaultTableModel)custTable.getModel();
            df.setRowCount(0);
            while(rs.next()){
                Vector v2 = new Vector();
                for(int i=1;i<=c;i++){
                    v2.add(rs.getString("cust_id"));
                    v2.add(rs.getString("Adhar_no"));
                    v2.add(rs.getString("driving_licence"));
                    v2.add(rs.getString("Cust_rating"));                        
                }
                df.addRow(v2);            
            }         
            
        }catch(ClassNotFoundException ex){
            Logger.getLogger(customerRegistration.class.getName()).log(Level.SEVERE,null,ex);            
        }catch(SQLException ex){
            Logger.getLogger(customerRegistration.class.getName()).log(Level.SEVERE,null,ex);
        }        
    }    
    private void custTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custTableMouseClicked
       

    }//GEN-LAST:event_custTableMouseClicked
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose();
        welcome w = new welcome();
        w.setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    private void defaultersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultersActionPerformed
        dispose();
        rentalInfo d = new rentalInfo();
        d.setVisible(true);
    }//GEN-LAST:event_defaultersActionPerformed

    private void returnCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnCarActionPerformed
        
        returnCar r = new returnCar();
        r.setVisible(true);
    }//GEN-LAST:event_returnCarActionPerformed

    private void customersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersActionPerformed
        dispose();
        users c = new users();
        c.setVisible(true);
    }//GEN-LAST:event_customersActionPerformed

    private void carRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carRegisterActionPerformed
        carRegistration c = new carRegistration();
        c.setVisible(true);
    }//GEN-LAST:event_carRegisterActionPerformed

    private void cancelledRentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelledRentsActionPerformed
        dispose();
        cancelledRecords c = new cancelledRecords();
        c.setVisible(true);

    }//GEN-LAST:event_cancelledRentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelledRents;
    private javax.swing.JButton carRegister;
    private javax.swing.JTable custTable;
    private javax.swing.JButton customers;
    private javax.swing.JButton defaulters;
    private javax.swing.JButton exit;
    private javax.swing.JScrollPane infoTable;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton returnCar;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables
}
